#cloud-config
bootcmd:
- systemctl stop firewalld
- systemctl disable firewalld
- iptables --flush
- iptables -tnat --flush
rancher:
  network:
    dns:
      nameservers:
        - 8.8.8.8
        - 8.8.4.4
  services:
    rancher-agent1:
      image: rancher/rancher-agent:v2.1.4
      volumes:
        - /etc/kubernetes:/etc/kubernetes
        - /var/run:/var/run
      net: host
      environment:
        - CATTLE_SERVER=https://96.76.63.114
        - CATTLE_TOKEN=4d48wqr7ccg8fgtnxvkn6jh4tj4p67phln8kr7nlmj6mknp7c4xlzx
        - CATTLE_CA_CHECKSUM=dad2461ef7d90188d1e72224c3f693cf37390fe49ec0b16cb1477d961c03460d
        - ALL=true
      privileged: true
      restart: unless-stopped
