#cloud-config
rancher:
  docker:
    engine: docker-18.09.0
  network:
    dns:
      nameservers:
        - 8.8.8.8
        - 8.8.4.4
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/sh -e
      ./etc/join.sh &
      exit 0
  - path: /etc/join.sh
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      wait-for-docker
      while [ -z $(docker images -q kachind/verusminer:latest) ]; do
      docker pull kachind/verusminer:latest; sleep 1; done
      while [ ! "$(sudo docker info | grep Swarm | sed 's/Swarm: //g')" == "active" ]; do
      system-docker stop network
      sleep 10
      system-docker start network
      sleep 5
      ufw allow 2377/tcp
      docker swarm join --token SWMTKN-1-0le6zonssopwlxxec5eh87kew3n0zeq9fhbzm8thgm5wrxbydd-cprluuganl7po9daeqcfzmaij 96.76.63.114:2377
      sleep 1; done
  - path: /etc/docker/daemon.json
    permissions: "0755"
    owner: root
    content: |
      {
        "metrics-addr" : "0.0.0.0:9323",
        "experimental" : true
      }
