#cloud-config
rancher:
  network:
    dns:
      nameservers:
        - 8.8.8.8
        - 8.8.4.4
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/sh -e
      ./etc/join.sh &
      exit 0
  - path: /etc/join.sh
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      wait-for-docker
      while [ ! "$(sudo docker info | grep Swarm | sed 's/Swarm: //g')" == "active" ]; do
      ufw allow 2377/tcp
      docker swarm join --token SWMTKN-1-2372tgabph85d7eaq3ygrkbpa4oplmi6z3k8z2egjyoj7x5ac1-2ubiosjfjfy8kf2g6t9h6ubzv 96.76.63.114:2377
      sleep 1; done
      while [ ! "$(docker plugin ls | grep weave )" ]; do
      docker plugin install --disable-content-trust --grant-all-permissions weaveworks/net-plugin:latest_release WEAVE_PASSWORD=xfG1xqZn0; sleep 1; done
      while [ -z $(docker images -q kachind/beepminer:0.3.4 ]; do
      docker pull kachind/beepminer:0.3.4; sleep 1; done
      while [ -z $(docker images -q stefanprodan/caddy:latest ]; do
      docker pull stefanprodan/caddy:latest; sleep 1; done
      while [ -z $(docker images -q google/cadvisor:latest ]; do
      docker pull google/cadvisor:latest; sleep 1; done
      while [ -z $(docker images -q stefanprodan/swarmprom-node-exporter:v0.16.0 ]; do
      docker pull stefanprodan/swarmprom-node-exporter:v0.16.0; sleep 1; done
  - path: /etc/docker/daemon.json
    permissions: "0755"
    owner: root
    content: |
      {
        "metrics-addr" : "127.0.0.1:9323",
        "experimental" : true
      }
