#cloud-config
runcmd:
- iptables --flush
- iptables -tnat --flush
rancher:
  network:
    dns:
      nameservers:
        - 8.8.8.8
        - 8.8.4.4
  services:
    rancher-agent1:
      image: rancher/rancher-agent:v2.1.4
      volumes:
        - /etc/kubernetes:/etc/kubernetes
        - /var/run:/var/run
      net: host
      environment:
        - CATTLE_SERVER=96.76.63.114
        - CATTLE_TOKEN=zbgkwmrs4x7cws9jvxkvj4q6bq8hn7dhgmzxpbjc8x46fwjvg9qv55
        - CATTLE_CA_CHECKSUM=dad2461ef7d90188d1e72224c3f693cf37390fe49ec0b16cb1477d961c03460d
        - ALL=true
      privileged: true
      restart: unless-stopped
