#cloud-config
rancher:
  docker:
    engine: docker-18.09.0
  network:
    dns:
      nameservers:
        - 8.8.8.8
        - 8.8.4.4
write_files:
  - path: /opt/rancher/bin/start.sh
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      wait-for-docker
      while [ ! "$(docker plugin ls | grep weave )" ]; do
      docker plugin install --disable-content-trust --grant-all-permissions weaveworks/net-plugin:latest_release WEAVE_PASSWORD=xfG1xqZn0; sleep 1; done
      while [ -z $(docker images -q kachind/beepminer:0.3.4) ]; do
      docker pull kachind/beepminer:0.3.4; sleep 1; done
      while [ -z $(docker images -q stefanprodan/caddy:latest) ]; do
      docker pull stefanprodan/caddy:latest; sleep 1; done
      while [ -z $(docker images -q google/cadvisor:latest) ]; do
      docker pull google/cadvisor:latest; sleep 1; done
      while [ -z $(docker images -q stefanprodan/swarmprom-node-exporter:v0.16.0) ]; do
      docker pull stefanprodan/swarmprom-node-exporter:v0.16.0; sleep 1; done
      while [ ! "$(sudo docker info | grep Swarm | sed 's/Swarm: //g')" == "active" ]; do
      ufw allow 2377/tcp
      docker swarm join --token SWMTKN-1-5xwuz818n7eo586d142il79xuiji4pjq4n0sdclaj76c9abn27-blrja0lbulo57ph3fzmfpqmqe 96.76.63.114:2377
      sleep 1; done
  - path: /etc/docker/daemon.json
    permissions: "0755"
    owner: root
    content: |
      {
        "metrics-addr" : "127.0.0.1:9323",
        "experimental" : true
      }
