#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC9Ovcx7at0tFJwmOkZrv3Uvte5578j8sgdeFFS7F71NRrIP/oJ6XczI7m/IAncLq3CmsjIZh++J/CpVSz+TL/VD///hCSVd5jfcg8CBSx0Cjc5u9HkyG5lS80uBvTQSKKNTvGgic6uzFPIcOx6LAD2OlAYqf4N7j4NQl87xenLw5X5MVP72VmZTPyaBttZk+hd4N2ziwtOYvEj6109XCfpxHc04KzzeoOmKmNxjr+wLbGnqVOh8WcXsrv/yzz/idduJ/p8RW0Ow6IVesLPQfYus9lVgqljGmuw10cQLJm1lEkVeTYNICD10ZAccDpjyGWiI5dmoCKJSPF/QyVMKZDih5IJvXqcoWhWYQX32MmaF7AqSWaMed9UAHoVP6W3lwQfnrIvZtAc6+AlvqxPHI6eLX0eHVOSmBtq8kYYUOr83gY17Y9uJEK451EktXQrCF0dPsX+TxkK5sqac1INCQ5UbMZgb7i4AQlqtqV6x7tH7vj1P0GJ9BhJf3tHBucGo4X2mHQoXSPWXkcL4m8pE92WPjlh0FlxJO62dQ0GEmMkOkDZKJSRsgPXV4qOazac532O2n99gNj5LwI8V/z7NckLD2R3UOwT9uxAAuldYyg6WL054dtaLxRT1ACKgJWW6NXA4Y+ZvIg2Aa3sxrXtD8fcD743jxEOFKDwWLT2gM/F9Q== key1@rancher
rancher:
  network:
    dns:
      nameservers:
        - 8.8.8.8
        - 8.8.4.4
  services:
    rancher-agent1:
      image: rancher/rancher-agent:v2.1.4
      volumes:
        - /etc/kubernetes:/etc/kubernetes
        - /var/run:/var/run
      net: host
      environment:
        - CATTLE_SERVER=https://96.76.63.114
        - CATTLE_TOKEN=kcgx44mpshn4pp88v9tw9mb5p2gsm4fzvkqxn9n58djsnbh6z8f7zx
        - CATTLE_CA_CHECKSUM=dad2461ef7d90188d1e72224c3f693cf37390fe49ec0b16cb1477d961c03460d
        - ALL=true
      privileged: true
      restart: unless-stopped
