#cloud-config
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC9Ovcx7at0tFJwmOkZrv3Uvte5578j8sgdeFFS7F71NRrIP/oJ6XczI7m/IAncLq3CmsjIZh++J/CpVSz+TL/VD///hCSVd5jfcg8CBSx0Cjc5u9HkyG5lS80uBvTQSKKNTvGgic6uzFPIcOx6LAD2OlAYqf4N7j4NQl87xenLw5X5MVP72VmZTPyaBttZk+hd4N2ziwtOYvEj6109XCfpxHc04KzzeoOmKmNxjr+wLbGnqVOh8WcXsrv/yzz/idduJ/p8RW0Ow6IVesLPQfYus9lVgqljGmuw10cQLJm1lEkVeTYNICD10ZAccDpjyGWiI5dmoCKJSPF/QyVMKZDih5IJvXqcoWhWYQX32MmaF7AqSWaMed9UAHoVP6W3lwQfnrIvZtAc6+AlvqxPHI6eLX0eHVOSmBtq8kYYUOr83gY17Y9uJEK451EktXQrCF0dPsX+TxkK5sqac1INCQ5UbMZgb7i4AQlqtqV6x7tH7vj1P0GJ9BhJf3tHBucGo4X2mHQoXSPWXkcL4m8pE92WPjlh0FlxJO62dQ0GEmMkOkDZKJSRsgPXV4qOazac532O2n99gNj5LwI8V/z7NckLD2R3UOwT9uxAAuldYyg6WL054dtaLxRT1ACKgJWW6NXA4Y+ZvIg2Aa3sxrXtD8fcD743jxEOFKDwWLT2gM/F9Q== key1@rancher
hostname: rancher-bitcolo
rancher:
  services:
    - beepminer1:
      - image: 
        - kachind/beepminer:0.3.4
      - restart: 
        - unless-stopped
    - beepminer2:
      - image: 
        - kachind/beepminer:0.3.4
      - restart: 
        - unless-stopped
    - beepminer3:
      - image: 
        - kachind/beepminer:0.3.4
      - restart: 
        - unless-stopped
    - beepminer4:
      - image: 
        - kachind/beepminer:0.3.4
      - restart: 
        - unless-stopped
