#cloud-config
rancher:
  network:
    dns:
      nameservers:
        - 8.8.8.8
        - 8.8.4.4
  services:
    exporter:
      image: prom/node-exporter:latest
      restart: unless-stopped
      ports:
        - '9100:9100'
      volumes:
        - /sys:/host/sys:ro
        - /:/rootfs:ro
        - /proc:/host/proc:ro
      deploy:
        mode: global
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/sh -e
      wait-for-docker
      ufw allow 2377/tcp
      docker swarm join --advertise-addr 96.76.63.113 --token SWMTKN-1-2372tgabph85d7eaq3ygrkbpa4oplmi6z3k8z2egjyoj7x5ac1-2ubiosjfjfy8kf2g6t9h6ubzv 96.76.63.114:2377
  - path: /etc/docker/daemon.json
    permissions: "0755"
    owner: root
    content: |
      {
        "metrics-addr" : "127.0.0.1:9323",
        "experimental" : true
      }
