#cloud-config
rancher:
  docker:
    engine: docker-18.06.1-ce
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      wait-for-docker
      ((count = 1000))
      while [[ $count -ne 0 ]] ; do
      ping -c 1 8.8.8.8
      rc=$?
      if [[ $rc -eq 0 ]] ; then
        ((count = 1))
      else
        echo "trying network restart"
        if [[ $count % 2 - eq 0 ]] ; then
          ifconfig eth1 up
          sleep 1
          ifconfig eth0 down
          sleep 1
          netconf
        else
          ifconfig eth0 up
          sleep 1
          ifconfig eth1 down
          sleep 1
          netconf
        fi
      fi
      ((count = count - 1))
      done
      while [ ! "$(sudo docker info | grep Swarm | sed 's/Swarm: //g')" == "active" ]; do
      ufw allow 2377/tcp
      docker swarm join --token SWMTKN-1-0le6zonssopwlxxec5eh87kew3n0zeq9fhbzm8thgm5wrxbydd-cprluuganl7po9daeqcfzmaij 96.76.63.114:2377
      sleep 1; done
      exit 0
