#cloud-config
runcmd:
  - docker swarm join --token SWMTKN-1-2372tgabph85d7eaq3ygrkbpa4oplmi6z3k8z2egjyoj7x5ac1-2ubiosjfjfy8kf2g6t9h6ubzv 96.76.63.114:2377
rancher:
  network:
    dns:
      nameservers:
        - 8.8.8.8
        - 8.8.4.4
  services:
    beepminer1:
      image: kachind/beepminer:0.3.4
      restart: unless-stopped
      net: host
    beepminer2:
      image: kachind/beepminer:0.3.4
      restart: unless-stopped
      net: host
    beepminer3:
      image: kachind/beepminer:0.3.4
      restart: unless-stopped
      net: host
    beepminer4:
      image: kachind/beepminer:0.3.4
      restart: unless-stopped
      net: host
    exporter:
      image: prom/node-exporter:latest
      ports:
        - '9100:9100'
      volumes:
        - /sys:/host/sys:ro
        - /:/rootfs:ro
        - /proc:/host/proc:ro
      deploy:
        mode: global
write_files:
  - path: /etc/docker/daemon.json
    permissions: "0755"
    owner: root
    content: |
      {
        "metrics-addr" : "127.0.0.1:9323",
        "experimental" : true
      }

#runcmd:
#- iptables --flush
#- iptables -tnat --flush
#rancher:
#  network:
#    dns:
#      nameservers:
#        - 8.8.8.8
#        - 8.8.4.4
#  services:
#    rancher-agent1:
#      image: rancher/rancher-agent:v2.1.4
#      volumes:
#        - /etc/kubernetes:/etc/kubernetes
#        - /var/run:/var/run
#      net: host
#      environment:
#        - SERVER=https://96.76.63.114:443
#        - TOKEN=k4j2vv77qzn6xqxxctvnxcxflg5m9xfdzxhhgrp789n24n2w5jpbrd
#        - CA_CHECKSUM=dad2461ef7d90188d1e72224c3f693cf37390fe49ec0b16cb1477d961c03460d
#        - WORKER=true
#      privileged: true
#      restart: unless-stopped
