#cloud-config
runcmd:
- iptables --flush
- iptables -tnat --flush
rancher:
  network:
    dns:
      nameservers:
        - 8.8.8.8
        - 8.8.4.4
  services:
    rancher-agent1:
      image: rancher/rancher-agent:v2.1.4
      volumes:
        - /etc/kubernetes:/etc/kubernetes
        - /var/run:/var/run
      net: host
      environment:
        - CATTLE_SERVER=96.76.63.114
        - CATTLE_TOKEN=k4j2vv77qzn6xqxxctvnxcxflg5m9xfdzxhhgrp789n24n2w5jpbrd
        - CATTLE_CA_CHECKSUM=dad2461ef7d90188d1e72224c3f693cf37390fe49ec0b16cb1477d961c03460d
        - WORKER=true
      privileged: true
      restart: unless-stopped
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/sh -e
      name=`ip -4 addr show enp4s0f0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}'`
      hostname=$(echo ${name} | tr  "."  "-")
      sudo ros config set hostname ${hostname}
      exit 0
